#localized string data for verbose messaging, errors, and warnings.

ConvertFrom-StringData @'
AddFacets = Adding facets to record
AddLabel = Adding image label {0}
DefineSyncHash = Defining synchronized hashtable
Ending = Ending PSBluesky module command
FacetLink = Creating link to {0}
FacetMention = Creating mention to {0}
FacetTag = Creating tag for {0}
FailAuthenticate = Failed to authenticate the Bluesky session
FailBlockList = Failed to retrieve blocked lists
FailBlockedUser = Failed to retrieve blocked user accounts
FailFeed = Failed to retrieve feed items for {0}. {1}
FailFollowers = Failed to retrieve followers
FailFollowing = Failed to retrieve following accounts
FailNotification = Failed to retrieve notifications. {0}
FailPDF = Failed to open the help file. {0}. You can try opening the help as markdown.
FailProfile = Failed to retrieve profile for {0}
FailRefresh = Failed to refresh or authenticate the Bluesky session. {0}. You might need to start a new session.
FailResolve = Failed to resolve {0}. {1} [{2}]
FailTimeline = Failed to retrieve timeline. {0}
FailUpload = Failed to upload image {0}. {1}
FailedLiked = Failed to retrieve likes for {0}. {1}
FilterNotification = Filtering notifications by type: {0}
FoundCommands = Found {0} functions
GetFunctions = Getting exported functions
GetModuleInfo = Getting module information for {0}
GetNotification = Retrieving {0} notifications
GetTimeline = Getting {0} timeline posts
MissingAlt = You must provide ALT text for the image!
NewFacet = Creating a new {0} facet for [{1}] in '{2}'
NewRunspace = Creating a new background runspace
NewSession = Creating a new Bluesky session for {0}
NoPost = You need to specify a message or an image!
NoSearchResults = No results found for {0}
NoSession = No Bluesky session detected. Run Start-BskySession to initialize a session.
OpenMarkdownHelp = Opening the help file as markdown
OpenPDFHelp = Attempting to open {0} with the default PDF viewer
PageBlockedLists = Getting all blocked lists
PageBlockedUsers = Getting all blocked user accounts
PageFollowers = Getting all followers from {0}
PageFollowing = Getting all following accounts from {0}
PageLikes = "Getting all liked posts from {0}
PostMessage = Creating message record
ProcessAccounts = Processing {0} accounts
ProcessCommand = Processing function {0}
ProcessMD = Processing Markdown style links
ProcessUrl = Processing URL links
PSVersion = Running under PowerShell version {0}
QueryFeed = Querying {0} feed items for {1}
QueryFollowers = Querying {0} followers for {1}
QueryFollowing = Querying {0} accounts followed by {1}
Quoting = Quoting the message with AT Uri {0}
RefreshSession = Refreshing a Bluesky logon session for {0}
Reposting = Reposting the message with AT Uri {0}
ResolveDID = Resolving the DiD for {0}
ResolveText = Resolving post text for {0}
RxEscape = Text requires regex escaping
SessionFound = Found an existing Bluesky session for {0}
Starting = Starting PSBluesky module command
StartRunspace = Starting the background runspace command
TextNotFound = The text {0} was not found in the message '{1}'
UploadImage = Uploading image {0} [{1}]
UserSearch = Searching for Bluesky user: {0}
UsingHost = Using PowerShell Host {0}
UsingModule = Using module PSBluesky version {0}
UsingOS = Running under Operating System {0}
'@